Feature: load mov as image background add audio in sequencer only no audio yet
Tilix4/OpenPype pull request #52
Opened 2023-07-05 09:05 UTC by kaamaurice

## Changelog Description
Loading mov as image background check if any sound in sequencers to add audio as sound sequence in an empty channel.

2023-07-05 13:08 UTC, Tilix4 requested changes
Nice! This is a much better design. Few optim

2023-07-05 13:08 UTC, Tilix4 commented on openpype/hosts/blender/plugins/load/load_image.py
> +            if all({seq.type != "SOUND" for seq in sequences}):
no need for setting up a `set`, a strict generator works, you can remove the brackets `{...}`

2023-07-05 13:08 UTC, Tilix4 commented on openpype/hosts/blender/plugins/load/load_image.py
> +                used_channels = {seq.channel for seq in sequences}
This variable is useless. You can move the built set to the `next` matching.

2023-07-05 15:52 UTC, kaamaurice commented on openpype/hosts/blender/plugins/load/load_image.py
> +                used_channels = {seq.channel for seq in sequences}
done

2023-07-06 07:33 UTC, Tilix4 approved these changes

2023-07-06 09:24 UTC, merged