Feature: Allow comment update for Kitsu Note
Tilix4/OpenPype pull request #81
Opened 2024-03-15 16:01 UTC by Tilix4

To be able to update a comment in a later publish, we have to split the note creation and the comment content update.  
For example, publishing a note with a render sent to a farm may need a note update in a second process, for displaying that the render has complete.

## Testing notes:
1. Everything should work as previously
2. Publish layout for `e666_sh005`, you can monitor Kitsu and see that the note is created first and then the comment content updated.

2024-03-18 18:43 UTC, Sharkitty requested changes
I wasn't able to get a review sent to kitsu when using the render farm.

2024-03-18 18:43 UTC, Sharkitty commented on openpype/modules/kitsu/plugins/publish/integrate_kitsu_comment.py
> +                "Kitsu comment status is different from the one in the instance, "
Line too long

2024-03-18 19:01 UTC, Tilix4 commented
> I wasn't able to get a review sent to kitsu when using the render farm.

The test doesn't mention the render farm, there is no point using it here. This feature allows future features for farm but doesn't rely on it. As described, publish should basically work like before with regular configuration (no render farm submission).

2024-03-18 19:11 UTC, Sharkitty commented
> > I wasn't able to get a review sent to kitsu when using the render farm.
> 
> The test doesn't mention the render farm, there is no point using it here. This feature allows future features for farm but doesn't rely on it. As described, publish should basically work like before with regular configuration (no render farm submission).

Oh okay, I did publish once without it and it worked normally in this case.

2024-03-19 13:17 UTC, Sharkitty approved these changes

2024-03-19 14:55 UTC, merged